### ISSUE TITLE
Problem modifying task.json

### ISSUE THREAD

**Issue by NicolasMalo1** [chrisWolter/saufi-website#37]
Hi, i'm trying to modify the ./src/assets/task.json file to change the language of the questions/challenges on the app but my modification aren't saved and the question/challenges stay as they were in German. Am I changing the wrong file ? Thank you

**Comment by alexHerrmi** [comment]
Hi there, sorry for responding so late. Currently the tasks are fetched from this URL https://alexherrmi.github.io/json/tasks.json 

if you want you can change the logic so it takes your local file. In Home.vue on line 128 we do the fetch.
